def addServer(serverName, url, showAdvanced=False):
    rightClick("menuServer.png")
    click("menuAddServer.png")
    type("txtServerName.png", serverName)
    paste(Pattern("txtTargetUrl.png").exact().targetOffset(-6,11), url)

    if (showAdvanced):
        click("tabAdvanced.png")
        click("rowBindAddress.png")
        type(Key.PAGE_DOWN)
        type(Key.PAGE_DOWN)
        type(Key.PAGE_DOWN)
        wait(1)
        click("tabBasic.png")
        
    click("btnAdd.png")

def addMap(mapName, url, showJsonView, fileResponse, content):
    rightClick("itemServer1.png")
    click("menuAddMap.png")
    rightClick("menuMap.png")
    click("menuRename.png")
    type(mapName)
    type(Key.ENTER)
    doubleClick("itemGetAllUser.png")
    click(Pattern("jsonRequestUrl.png").targetOffset(8,1))
    paste(url)
    if (showJsonView):
        click("tabJsonView.png")
        click("tabRaw.png")
    click("btnSave.png")
    click("btnClose.png")
    doubleClick(fileResponse)
    click("txtResponseContent.png")
    type("a", KeyModifier.CTRL)
    paste(content)
    rightClick(Location(581, 207))
    click("menuJson.png")
    click("jsonFormat.png")
    
addServer("server1", "http://www.g1.com.br")
addMap("GetAllUser", "user/all", True, "responseGetAllUser.png", '[{"Name":"User1","Age":20},{"Name":"User2","Age":21}]')
addMap("GetUser1", "user/1", False, "itemGetUser1.png", '{"Name":"User1","Age":20}')
addMap("GetUser2", "user/2", False, "itemGetUser2.png", '{"Name":"User2","Age":50}')
addMap("GetUser2-alternative", "user/2", False, "itemGetUserAlternative.png", '{"Name":"User2","Age":50, "otherAttribute": 10}')

#doubleClick("responseGetAllUser.png")
#click("txtResponseContent.png")
#type("a", KeyModifier.CTRL)
#paste('[{"Name":"User1","Age":20},{"Name":"User2","Age":21}]')
#rightClick(Location(581, 207))
#click("menuJson.png")
#click("jsonFormat.png")
wait(4)