def doubleClick2(img):
    if isinstance(img, str):
        find(img)
    doubleClick(img)

def click2(img):
    if isinstance(img, str):
        find(img)
    click(img)

# fix error: the "/" char not working with type
# fix erro2: paste sometimes not work, add wait
def type2(value):
    if ('/' in value):
        wait(2)
        paste(value)
    else:
        type(value)

def rightClick2(img):
    if isinstance(img, str):
        print 1
        find(img)
    rightClick(img)

#click("aa.png")
#print("/")
#keyDown(Key.CTRL)
#keyDown("@")
#type("/")

def addServer(serverName, url, showAdvanced=False):
    if exists("menuServer.png"):
        rightClick2("menuServer.png")
    else:
        rightClick2("Sewers.png")

    click2("menuAddServer.png")
    #type(Pattern("txtServerName.png").targetOffset(-8,8), serverName)
    wait(1)
    type2(serverName)
    type(Key.TAB)
    type2(url)
    wait(1)
    
    if (showAdvanced):
        click2("tabAdvanced.png")
        click2("rowBindAddress.png")
        type(Key.PAGE_DOWN)
        type(Key.PAGE_DOWN)
        type(Key.PAGE_DOWN)
        wait(1)
        click2("tabBasic.png")
        
    click2("btnAdd.png")

def addMap(mapName, url, showJsonView, fileResponse, content):
    rightClick2("itemServer1.png")
    click2("menuAddMap.png")
    rightClick2("menuMap.png")
    click2("menuRename.png")
    type2(mapName)
    type(Key.ENTER)
    doubleClick2("itemGetAllUser.png")
    click2(Pattern("jsonRequestUrl.png").targetOffset(8,1))
    type2(url)
    if (showJsonView):
        click2("tabJsonView.png")
        click2("tabRaw.png")
    click2("btnSave.png")
    click2("btnClose.png")
    doubleClick2(fileResponse)
    click2("txtResponseContent.png")
    type("a", KeyModifier.CTRL)
    type2(content)
    rightClick2(Location(581, 207))
    click2("menuJson.png")
    click2("jsonFormat.png")
    click2("btnSave.png")
    click2("btnClose.png")

def duplicateMap(mapFrom, mapTo, fileResponse, mapName, content):
    rightClick2(mapFrom)
    click2("DuplicateCtr.png")
    rightClick2(mapTo)
    click2("menuRename.png")
    type2(mapName)
    type(Key.ENTER)
    doubleClick2(mapTo)
    doubleClick2(fileResponse)
    click2(Location(563, 226))
    type("a", KeyModifier.CTRL)
    type2(content)
    rightClick2(Location(581, 207))
    click2("menuJson.png")
    click2("jsonFormat.png")
    click2("btnSave.png")
    click2("btnClose.png")

def startInChrome(url, server, view, chromeUrl):
    rightClick2(server)
    click2("start.png")
    wait(3)
    click2(view)
    click2(chromeUrl)
    type2(url)
    type(Key.ENTER)
    wait(2)
    click2("close.png")

def logViewContent():
    rightClick2("NETIN.png")
    click2("ViewContent.png")
    click2(Pattern("closeViewContent.png").targetOffset(24,0))

def logWebRequest():
    rightClick2("listener.png")
    click2("OpeninWebReq.png")
    wait(1)
    click2("execute.png")
    wait(1) 
    click2(Pattern("webRequestClose.png").targetOffset(29,-3))

def callInWebRequest(map):
    if (map):
        rightClick2(map)
        click2("ViewinWebReq.png")
    click2("execute.png")
    wait(2)

def toggleMap(map):
    rightClick2(map)
    click2("Enable.png")

def createPost(mapName, url, fileResponse, content):
    rightClick2("itemServer1.png")
    click2("menuAddMap.png")
    rightClick2("menuMap.png")
    click2("menuRename.png")
    type2(mapName)
    type(Key.ENTER)
    doubleClick2("itemGetAllUser.png")
    click2(Pattern("jsonRequestUrl.png").targetOffset(8,1))
    type2(url)
    click2(Pattern("methodGET.png").targetOffset(13,3))
    type(Key.DELETE)
    type(Key.DELETE)
    type(Key.DELETE)
    type(Key.DELETE)
    type2("POST\",")
    click2(Pattern("methodPOST.png").targetOffset(47,0))
    type(Key.ENTER)
    type2("    \"bodyPatterns\" : [{\n         \"equalToJson\" : \"{\"Name\":\"User3\",\"Age\":60}\"\n     }]")
    click2(Pattern("User3Ace60Na.png").targetOffset(-70,1))
    type(Key.END, KeyModifier.SHIFT)
    type(Key.LEFT, KeyModifier.SHIFT)
    type(Key.LEFT, KeyModifier.SHIFT)
    rightClick2("NameUser3ae6.png")
    click2("Json.png")
    click2("Escape.png")    
    click2(Pattern("NameUser3Age.png").targetOffset(-82,1))
    type(Key.END, KeyModifier.SHIFT)
    type(Key.LEFT, KeyModifier.SHIFT)
    type(Key.LEFT, KeyModifier.SHIFT)
    rightClick2("NameUser3Aae.png")
    click2("Json.png")
    click2("Editvalue.png")
    click2(Pattern("Qe60H.png").targetOffset(3,-1))
    type(Key.DELETE)
    type(Key.DELETE)
    type2("100")
    click2("btnReplace.png")
    click2("btnSave.png")
    click2("btnClose.png")
    doubleClick2(fileResponse)
    click2("txtResponseContent.png")
    type("a", KeyModifier.CTRL)
    type2(content)
    rightClick2(Location(581, 207))
    click2("menuJson.png")
    click2("jsonFormat.png")
    click2("btnSave.png")
    click2("btnClose.png")

def compareTest():
    click2("Tool.png")
    click2("ebRequest.png")
    click2(Location(505, 94))
    click2("POST.png")
    click2(Pattern("urlWR.png").targetOffset(-285,-1))
    type2("http://localhost:5500/user/insert")
    click2(Pattern("BodyHeaderFi.png").targetOffset(-49,2))
    click2(Pattern("HeadersBdYHe.png").targetOffset(-75,3))
    type2('{"Name":"User3","Age":60}')
    rightClick2(Location(524, 169))
    click2("menuJson.png")
    click2("jsonFormat.png")
    click2("execute.png")
    wait(2)
    click2("Scenario1Sta.png")
    rightClick2("POSTuserinse.png")
    click2("Compare.png")
    click2(Location(1338, 86))
    click2("Selectinthet.png")
    doubleClick2(Pattern("userInsertns.png").targetOffset(-45,-5))
    click2("compare-1.png")
    wait(4)
    click2("00009Age60.png")
    wait(1)
    click2(Pattern("closeCompare.png").targetOffset(-5,-8))
    click2(Pattern("usernsert.png").targetOffset(31,-3))
    click2("Scenario1Sta.png")
    click2("btnClean.png")
    click2("WebRequest.png")
    click2(Pattern("HAgeH.png").targetOffset(10,1))
    type(Key.DELETE)
    type(Key.DELETE)
    type2("100")
    click2("execute.png")
    wait(2)
    click2("Scenario1Sta.png")
    rightClick2("LISTENERlPOS.png")
    click2("Compare.png")
    click2(Location(1338, 86))
    click2("Selectinthet.png")
    doubleClick2(Pattern("userInsertns.png").targetOffset(-45,-5))
    click2("compare-1.png")
    wait(2)
    click2(Pattern("closeCompare.png").targetOffset(-5,-8))
    click2(Pattern("usernsert.png").targetOffset(31,-3))
    click2(Pattern("WebRequest.png").targetOffset(41,-2))

def testCreateNotExistsAPI():
    addServer("server1", "")
    addMap("GetAllUser", "user/all", True, "responseGetAllUser.png", '[{"Name":"User1","Age":20},{"Name":"User2","Age":21}]')
    addMap("GetUser1", "user/1", False, "itemGetUser1.png", '{"Name":"User1","Age":20}')
    addMap("GetUser2", "user/2", False, "itemGetUser2.png", '{"Name":"User2","Age":50}')
    duplicateMap("user2GetUser-1.png", Location(145, 201), "GetUser2aite.png", "GetUser2-alternative", '{"Name":"User2","Age":50, "otherAttribute": 10}')
    createPost("InsertUser", "user/insert", "InsertUser.png", '{"status":"OK"}')
    startInChrome("http://localhost:5500/user/all", "server1.png", Pattern("view.png").targetOffset(268,4), Pattern("chromeUrl.png").targetOffset(47,-2))
    logViewContent()
    logWebRequest()
    callInWebRequest("user2GetUser.png")
    toggleMap("user2GetUser.png")
    callInWebRequest(None)
    compareTest()

def testRecord():
    addServer("server2", "https://www.w3schools.com/")    
    rightClick2("server2.png")
    click2("StartandReco.png")
    wait(2)
    click2(Pattern("ServerUrIhtt.png").targetOffset(271,1))
    wait(5)
    click2("close.png")
    click2(Pattern("Imagescolorp.png").targetOffset(-71,1))
    doubleClick2("bodyimagesco.png")
    click2(Pattern("D99.png").targetOffset(11,0))
    rightClick2("server2-1.png")
    click2("StOP.png")
    rightClick2("server2.png")
    click2("start.png")    
    click2(Pattern("mappingroOI.png").targetOffset(-51,1))
    doubleClick2("mmrml.png")
    click2(Pattern("drteW3Schoos.png").targetOffset(-81,1))
    type(Key.END, KeyModifier.SHIFT)
    for num in range(1,10):
        type(Key.LEFT, KeyModifier.SHIFT)
    type(Key.DELETE)
    type2("OTHER TITLE")
    click2("btnSave.png")
    click2("btnClose.png")
    click2("Scenario1Sta-1.png")    
    click2(Pattern("ServerUrIhtt.png").targetOffset(271,1))
    wait(4)
    type(Key.DELETE, KeyModifier.CTRL + KeyModifier.SHIFT)
    wait(4)
    click2("LIMPARDADOSD.png")
    click2(Pattern("Jragoes.png").targetOffset(47,-2))
    type(Key.F5)
    wait(3)
    click2("close.png")
    testShowInfo()
    
def testShowInfo():
    rightClick2(Pattern("server2httpI.png").targetOffset(11,9))
    click2("ShowName.png")
    wait(2)

def testProxy():
    
    addServer("server3", "http://wiremock.org/")
    rightClick2("server3.png")
    click2("StartOnlyPro.png")
    wait(2)
    click2(Pattern("ServerUrIhtt-1.png").targetOffset(271,1))
    wait(5)
    click2("close.png")
    wait(3)
    
    click("scroll.png")
    type(Key.PAGE_UP)
    type(Key.PAGE_UP)
    type(Key.PAGE_UP)
    type(Key.PAGE_UP)
    click(Pattern("NETNGET-1.png").targetOffset(259,1))
    keyDown(Key.CTRL)
    click(Pattern("LISTENERlGET.png").targetOffset(268,2))
    click("Differenceof.png")
    wait(4)
    
def cleanChromeCache():
    click("chrome.png")
    click(Pattern("om.png").targetOffset(14,-3))
    type(Key.DELETE, KeyModifier.CTRL + KeyModifier.SHIFT)
    wait(4)
    click2("LIMPARDADOSD.png")
    click2(Pattern("Jragoes.png").targetOffset(47,-2))
    
cleanChromeCache()
testCreateNotExistsAPI()
testRecord()
testProxy()